In [1]:
z_prjs_file = '/Users/uqhsun8/Documents/MATLAB/scripts/pytorch_codes/image_unet_stack_prjs/z_prjs.txt'

In [2]:
        z_prjs_arr = [line.strip().split(" ") for line in open(z_prjs_file)]
        # convert z_prjs into a dic
        z_prjs_keys = [z_prjs_arr[i][0] for i in range(0, len(z_prjs_arr))]
        z_prjs_values = [z_prjs_arr[i][1:4] for i in range(0, len(z_prjs_arr))]
        z_prjs_dict = dict(zip(z_prjs_keys, z_prjs_values))

In [4]:
list_path = '/Users/uqhsun8/Documents/MATLAB/scripts/pytorch_codes/invivo_IDs.txt'

In [5]:
img_ids = [i_id.strip() for i_id in open(list_path)]

In [9]:
root = '/Volumes/LaCie/CommQSM/invivo/data_for_training'
files = []

In [10]:
        for name in img_ids:
            field_file = root + \
                ("/field/field_%s.nii" % name)
            label_file = root + ("/chi/chi_%s.nii" % name)
            files.append({
                "field": field_file,
                "prjs": z_prjs_dict[name],
                "label": label_file,
                "name": name
            })

In [11]:
files

[{'field': '/Volumes/LaCie/CommQSM/invivo/data_for_training/field/field_1-1.nii',
  'prjs': ['-0.414076', '0.030108', '0.909744'],
  'label': '/Volumes/LaCie/CommQSM/invivo/data_for_training/chi/chi_1-1.nii',
  'name': '1-1'},
 {'field': '/Volumes/LaCie/CommQSM/invivo/data_for_training/field/field_1-2.nii',
  'prjs': ['0.335277', '0.054866', '0.940521'],
  'label': '/Volumes/LaCie/CommQSM/invivo/data_for_training/chi/chi_1-2.nii',
  'name': '1-2'},
 {'field': '/Volumes/LaCie/CommQSM/invivo/data_for_training/field/field_1-3.nii',
  'prjs': ['0.000048', '-0.066274', '0.997801'],
  'label': '/Volumes/LaCie/CommQSM/invivo/data_for_training/chi/chi_1-3.nii',
  'name': '1-3'},
 {'field': '/Volumes/LaCie/CommQSM/invivo/data_for_training/field/field_1-4.nii',
  'prjs': ['0.035859', '0.317561', '0.947560'],
  'label': '/Volumes/LaCie/CommQSM/invivo/data_for_training/chi/chi_1-4.nii',
  'name': '1-4'},
 {'field': '/Volumes/LaCie/CommQSM/invivo/data_for_training/field/field_1-5.nii',
  'prjs': ['

In [12]:
index = 2

In [13]:
datafiles = files[index]

In [14]:
datafiles

{'field': '/Volumes/LaCie/CommQSM/invivo/data_for_training/field/field_1-3.nii',
 'prjs': ['0.000048', '-0.066274', '0.997801'],
 'label': '/Volumes/LaCie/CommQSM/invivo/data_for_training/chi/chi_1-3.nii',
 'name': '1-3'}

In [19]:
import nibabel as nib
name = datafiles["name"]
# nifti read codes.
nibfield = nib.load(datafiles["field"])
niblabel = nib.load(datafiles["label"])
import numpy as np

In [22]:
        field = nibfield.get_data()
        label = niblabel.get_data()

        field = np.array(field)
        label = np.array(label)

/Users/uqhsun8/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
  """Entry point for launching an IPython kernel.
/Users/uqhsun8/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
  


In [93]:
prjs_elements

array([ 4.80000e-05, -6.62740e-02,  9.97801e-01])

In [82]:
prjs_elements = np.array([float(i) for i in datafiles["prjs"]])

In [88]:
        size_prjs = list(field.shape)
        size_prjs.append(prjs_elements.size)
        prjs = prjs_elements*np.ones(size_prjs)

In [98]:
prjs.shape

(48, 48, 48, 3)

In [99]:
field.shape

(48, 48, 48)

In [81]:
size_prjs

[3, [48, 48, 48]]

In [68]:
size_prjs.append(prjs_elements.size)

In [69]:
size_prjs

[48, 48, 48, 3]

In [72]:
prjs_elements

array([ 4.80000e-05, -6.62740e-02,  9.97801e-01])

In [70]:
np.ones(size_prjs)*prjs_elements

array([[[[ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         ...,
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01]],

        [[ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         ...,
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01]],

        [[ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         ...,
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01],
         [ 4.80000e-05, -6.62740e-02,  9.97801e-01]],

In [61]:
b = a.append(prjs_elements.size)

In [66]:
a